name: flutter_netcore
description: "NetworkManager for Flutter applications."
version: 0.0.1

homepage: https://github.com/safauludogan/flutter_netcore

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Network
  dio: ^5.9.0

  # Utils
  logger: ^2.6.2
  retry: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  very_good_analysis: ^10.0.0
  test: ^1.26.3
  mocktail: ^1.0.4
